name: Release Actions
on:
  push:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: setup semantic-release
      - run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D
      - name: release
      - run: npx semantic-release